/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import main.Shop;
import model.Amount;
import model.Product;

/**
 *
 * @author iancl
 */
public class ProductView extends javax.swing.JDialog {

    int option;
    Shop shop;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductView.class.getName());

    /**
     * Creates new form ProductView
     */
    public ProductView(java.awt.Frame parent, boolean modal, int option, Shop shop) {
        super(parent, modal);
        initComponents();
        this.option = option;
        this.shop = shop;
        if (option == 3) {
            PrecioProducto.setVisible(false);
            PProduct.setVisible(false);
        } else if (option == 9) {
            PrecioProducto.setVisible(false);
            PProduct.setVisible(false);
            StockProducto.setVisible(false);
            SProduct.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StockProducto = new javax.swing.JLabel();
        PrecioProducto = new javax.swing.JLabel();
        NProduct = new javax.swing.JTextField();
        SProduct = new javax.swing.JTextField();
        PProduct = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre producto:");

        StockProducto.setText("Stock producto:");

        PrecioProducto.setText("Precio producto:");

        NProduct.addActionListener(this::NProductActionPerformed);

        SProduct.addActionListener(this::SProductActionPerformed);

        OK.setText("OK");
        OK.addActionListener(this::OKActionPerformed);

        Cancel.setText("Cancel");
        Cancel.addActionListener(this::CancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(StockProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrecioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cancel)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(NProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockProducto)
                    .addComponent(SProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioProducto)
                    .addComponent(PProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(Cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NProductActionPerformed

    private void SProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SProductActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        switch (option) {
            case 2:

                //System.out.println("en el 2");
                //  leer datos de la ventana
                String name = NProduct.getText();
                int stock = Integer.parseInt(SProduct.getText());
                double price = Double.parseDouble(PProduct.getText());
                Amount wholesalerPrice = new Amount(price);

                if (shop.findProduct(name) == null) {

                    Product p = new Product(name, wholesalerPrice, true, stock);
                    shop.addProduct(p);
                    JOptionPane.showMessageDialog(this, name + " añadido correctamente", "Info", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, " Este producto ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                }

                break;
            case 3:
                //System.out.println("en el 3");

                // add stock product
                String nameStock = NProduct.getText();
                Product found = shop.findProduct(nameStock);

                if (found != null) {
                    int stock3 = Integer.parseInt(SProduct.getText());
                    int TotalStock = found.getStock() + stock3;
                    found.setStock(TotalStock);
                    JOptionPane.showMessageDialog(this, "Stock actualizado", "Info", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Producto no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
                }

                break;
            case 9:
                // remove product
                //System.out.println("en el 9");

                String nameDProduct = NProduct.getText();
                Product productoABorrar = shop.findProduct(nameDProduct);

                if (shop.findProduct(nameDProduct) != null) {
                    Shop.inventory.remove(productoABorrar);
                    JOptionPane.showMessageDialog(this, "Producto eliminado", "Info", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Producto no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
                }

                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_OKActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField NProduct;
    private javax.swing.JButton OK;
    private javax.swing.JTextField PProduct;
    private javax.swing.JLabel PrecioProducto;
    private javax.swing.JTextField SProduct;
    private javax.swing.JLabel StockProducto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
