/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import main.Shop;

/**
 *
 * @author iancl
 */
public class ShopView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShopView.class.getName());

    private Shop shop;

    /**
     * Creates new form ShopView
     */
    public ShopView() {
        initComponents();
        shop = new Shop();

        shop.loadInventory();
        setupKeyBindings();
        
        // Eliminar los KeyListeners de los botones
        CashV.removeKeyListener(CashV.getKeyListeners()[0]);
        ProductAddV.removeKeyListener(ProductAddV.getKeyListeners()[0]);
        StockAddV.removeKeyListener(StockAddV.getKeyListeners()[0]);
        DeletePV.removeKeyListener(DeletePV.getKeyListeners()[0]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        CashV = new javax.swing.JButton();
        ProductAddV = new javax.swing.JButton();
        StockAddV = new javax.swing.JButton();
        DeletePV = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione o pulse una opción");

        CashV.setText("1. Contar caja");
        CashV.addActionListener(this::CashVActionPerformed);
        CashV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CashVKeyPressed(evt);
            }
        });

        ProductAddV.setText("2. Añadir producto");
        ProductAddV.addActionListener(this::ProductAddVActionPerformed);
        ProductAddV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProductAddVKeyPressed(evt);
            }
        });

        StockAddV.setText("3. Añadir stock");
        StockAddV.addActionListener(this::StockAddVActionPerformed);
        StockAddV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StockAddVKeyPressed(evt);
            }
        });

        DeletePV.setText("9. Eliminar producto");
        DeletePV.addActionListener(this::DeletePVActionPerformed);
        DeletePV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DeletePVKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CashV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(StockAddV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductAddV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeletePV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(CashV)
                .addGap(18, 18, 18)
                .addComponent(ProductAddV)
                .addGap(18, 18, 18)
                .addComponent(StockAddV)
                .addGap(18, 18, 18)
                .addComponent(DeletePV)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductAddVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductAddVActionPerformed
         openProductView(2);
    }//GEN-LAST:event_ProductAddVActionPerformed

    private void CashVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashVActionPerformed
         openCashView(1);
    }//GEN-LAST:event_CashVActionPerformed

    private void StockAddVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockAddVActionPerformed
         openProductView(3);

    }//GEN-LAST:event_StockAddVActionPerformed

    private void DeletePVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePVActionPerformed
         openProductView(9);
    }//GEN-LAST:event_DeletePVActionPerformed

    private void CashVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashVKeyPressed
        // TODO add your handling code here:
        openCashView(1);
    }//GEN-LAST:event_CashVKeyPressed

    private void ProductAddVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductAddVKeyPressed
        // TODO add your handling code here:
        openProductView(2);
    }//GEN-LAST:event_ProductAddVKeyPressed

    private void StockAddVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockAddVKeyPressed
        // TODO add your handling code here:
        openProductView(3);
    }//GEN-LAST:event_StockAddVKeyPressed

    private void DeletePVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DeletePVKeyPressed
        // TODO add your handling code here:
        openProductView(9);
    }//GEN-LAST:event_DeletePVKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShopView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CashV;
    private javax.swing.JButton DeletePV;
    private javax.swing.JButton ProductAddV;
    private javax.swing.JButton StockAddV;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void openCashView(int par) {
        CashView dialog = new CashView(this, rootPaneCheckingEnabled,shop);
        dialog.setLocationRelativeTo(this);
        dialog.setModal(true);
        dialog.setVisible(true);

    }

    private void openProductView(int par) {
        ProductView dialog = new ProductView(this, rootPaneCheckingEnabled, par, shop);
        dialog.setLocationRelativeTo(this);
        dialog.setModal(true);
        dialog.setVisible(true);

    }

    public void keyPressed(KeyEvent e) {
        // TODO Auto-generated method stub
        System.out.println("hola");
        if (e.getKeyChar() == KeyEvent.VK_1) {
            this.openCashView(1);
        }
        if (e.getKeyChar() == KeyEvent.VK_2) {
            this.openProductView(2);
        }
        if (e.getKeyChar() == KeyEvent.VK_3) {
            this.openProductView(3);
        }
        if (e.getKeyChar() == KeyEvent.VK_9) {
            this.openProductView(9);
        }
    }

    private void setupKeyBindings() {
        javax.swing.InputMap im = getRootPane().getInputMap(
                javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        javax.swing.ActionMap am = getRootPane().getActionMap();

        im.put(javax.swing.KeyStroke.getKeyStroke('1'), "openCash");
        im.put(javax.swing.KeyStroke.getKeyStroke('2'), "openProduct2");
        im.put(javax.swing.KeyStroke.getKeyStroke('3'), "openProduct3");
        im.put(javax.swing.KeyStroke.getKeyStroke('9'), "openProduct9");

        am.put("openCash", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                openCashView(1);
            }
        });
        am.put("openProduct2", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                openProductView(2);
            }
        });
        am.put("openProduct3", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                openProductView(3);
            }
        });
        am.put("openProduct9", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                openProductView(9);
            }
        });
    }

}
